"""Version information."""
__title__ = "ctrw"
__description__ = "Nummerical simulation of a uncoupled Continious Time Random Walk realization"
__url__ = "test"
__version__ = "0.1.0"
__author__ = "Daniel Zalami"
__author_email__ = "mail@daniel-zalami.de"
__license__ = "MIT"
__copyright__ = "Copyright 2020 Daniel Zalami"
__docs_copyright__ = "2020 Daniel Zalami"
